<?php

/**
 * Created by PhpStorm.
 * User: jack
 * Date: 3/20/2018
 * Time: 10:27 AM
 */
class A
{
    public static function who()
    {
        echo __CLASS__;
    }

    public static function test()
    {
        //self ::who();
        static ::who();
    }
}

class B extends A
{
    public static function who()
    {
        //parent ::who(); // TODO: Change the autogenerated stub
        echo __ClASS__;
    }
}

B ::test();
